clase-5/demo/config/routes.rb
Rails.application.routes.draw do
  get '/hola' => 'saludo#hola'
  resources :usuarios
  resources :productos

end

clase-5/demo/app/models/producto.rb
class Producto < ActiveRecord::Base
end

clase-5/demo/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates_presence_of :nombre
end

clase-5/demo/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:titulo, :descripcion, :precio)
    end
end

clase-5/demo/app/controllers/saludo_controller.rb
class SaludoController < ApplicationController
  def hola
    @mensaje = 'Hola RCP'
  end
end

clase-5/demo/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def index
    @usuarios = Usuario.all
  end

  def show
    @usuario = Usuario.find(params[:id])
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      redirect_to @usuario
    else
      render json: 'No se pudo guardar el usuario'
    end
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
    @usuario.update(usuario_params)
    redirect_to @usuario
  end

  def destroy
    @usuario = Usuario.find(params[:id]).destroy
    redirect_to '/usuarios'
  end

  private

  def usuario_params
    params.require(:usuario).permit(:nombre, :edad)
  end
end

clase-5/demo/app/helpers/productos_helper.rb
module ProductosHelper
end

clase-5/demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

clase-5/demo/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clase-5/demo/app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

clase-5/demo/app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.titulo %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.precio %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

clase-5/demo/app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

clase-5/demo/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @producto.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @producto.precio %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>

clase-5/demo/app/views/saludo/hola.html.erb
<h1><%= @mensaje %></h1>

clase-5/demo/app/views/usuarios/edit.html.erb
<%= form_for(@usuario) do |f| %>
  <label for="">Nombre</label>
  <%= f.text_field :nombre %>

  <%= f.label :edad %>
  <%= f.text_field :edad %>

  <%= f.submit 'Actualizar' %>
<% end %>

clase-5/demo/app/views/usuarios/index.html.erb
<h1>Usuarios</h1>
<ul>
  <% @usuarios.each do |usuario| %>
    <li><%= link_to usuario.nombre, usuario, id: 'clase' %></li>
  <% end %>
</ul>
<%= link_to 'Nuevo usuario', new_usuario_path %>

clase-5/demo/app/views/usuarios/new.html.erb
<%= form_for(@usuario) do |f| %>
  <label for="">Nombre</label>
  <%= f.text_field :nombre %>

  <%= f.label :edad %>
  <%= f.text_field :edad %>

  <%= f.submit 'Crear' %>
<% end %>

clase-5/demo/app/views/usuarios/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @usuario.nombre %>
</p>
<p>
  <b>Edad:</b>
  <%= @usuario.edad %>
</p>

<%= link_to 'Editar', edit_usuario_path %>
<%= link_to 'Eliminar', usuario_path, method: :delete %>